---
kind: pipeline
type: docker
name: test

steps:
- name: build
  image: karrug/dsin100dayscicd:0.3
  commands:
  - pwd
  - df -h
  - /root/env/bin/python tools/buildhtmlpages.py

trigger:
  event:
  - pull_request


---
kind: pipeline
type: docker
name: stage

steps:
- name: build
  image: karrug/dsin100dayscicd:0.3
  commands:
  - pwd
  - df -h
  - /root/env/bin/python tools/buildhtmlpages.py

- name: deploy
  image: karrug/dsin100dayscicd:0.3
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
  - AWS_ACCESS_KEY_ID=$${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=$${AWS_SECRET_ACCESS_KEY} /root/env/bin/aws s3 sync --acl public-read content s3://refactoredstage/dsin100days/content
  - /root/env/bin/aws s3 sync --acl public-read micro_courses s3://refactoredstage/dsin100days/micro_courses
 
trigger:
  branch:
  - develop
  event:
  - push


---
kind: pipeline
type: docker
name: live

steps:
- name: build
  image: karrug/dsin100dayscicd:0.3
  commands:
  - ip addr
  - whoami
  - pwd
  - /root/env/bin/python tools/buildhtmlpages.py

- name: deploy
  image: karrug/dsin100dayscicd:0.3
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID_LIVE
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY_LIVE
  commands:
  - AWS_ACCESS_KEY_ID=$${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=$${AWS_SECRET_ACCESS_KEY} /root/env/bin/aws s3 sync --acl public-read content s3://refactored/dsin100days/content
  - /root/env/bin/aws s3 sync --acl public-read micro_courses s3://refactored/dsin100days/micro_courses
 
trigger:
  branch:
  - master
  event:
  - push
