def sliders_init():
    import ipywidgets as widgets
    m1=widgets.FloatSlider(
    value=0.1,
    min=0.01,
    max=0.15,
    step=0.01,
    description='Marker1:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='.2f',
    )
    m2=widgets.FloatSlider(
    value=0.25,
    min=0.16,
    max=0.35,
    step=0.01,
    description='Marker2:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='.2f',
    )

    m3=widgets.FloatSlider(
    value=0.5,
    min=0.36,
    max=0.5,
    step=0.01,
    description='Marker3:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='.2f',
    )
    return(m1,m2,m3)
