def sliders_init_reward():
    import ipywidgets as widgets
    r1=widgets.FloatSlider(
    value=0.5,
    min=0.1,
    max=1,
    step=0.01,
    description='Reward1:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='.2f',
    )

    r2=widgets.FloatSlider(
    value=0.5,
    min=0.1,
    max=1,
    step=0.01,
    description='Reward2:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='.2f',
    )

    r3=widgets.FloatSlider(
    value=0.5,
    min=0.1,
    max=1,
    step=0.01,
    description='Reward3:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='.2f',
    )
    r4=widgets.FloatSlider(
    value=0.005,
    min=0,
    max=0.05,
    step=0.0001,
    description='Reward4:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='.3f',
    )
    return(r1,r2,r3,r4)
